[package]
name = "r_dns-amplifier"
version = "0.1.0"
authors = ["David Stromberger <Davidstromberger99@gmx.de>"]
edition = "2021"

[[bin]]
name = "amplifier"
path = "src/amplifier.rs"

[dependencies]
reqwest = { version = "0.11.6", features = ["blocking"] }
tokio = { version = "1.27.0", features = ["full"] }
byteorder = "1.4.3"
clap = { version = "4.2.1", features = ["derive"] }
trust-dns-resolver = "0.22.0"
trust-dns-proto = "0.22.0"

